## Parameter Mapping
# InvenTree:Digi-Key
Capacitors:
  Value:
  - Capacitance
  Rated Voltage:
  - Voltage - Rated
  Tolerance:
  - Tolerance
  ESR:
  - ESR (Equivalent Series Resistance)
  Package Type:
  - Package / Case
  Package Size:
  - Size / Dimension
  Package Height:
  - Height - Seated (Max)
  Temperature Grade:
  - Temperature Coefficient
  Temperature Range:
  - Operating Temperature
Circuit Protections:
  Value:
  - Manufacturer Part Number
  Capacitance:
  - Capacitance @ Frequency
  Rated Voltage:
  - Voltage Rating - DC
  Rated Current:
  - Current Rating (Amps)
  Rated Power:
  - Power - Peak Pulse
  Standoff Voltage:
  - Voltage - Reverse Standoff (Typ)
  Breakdown Voltage:
  - Voltage - Breakdown (Min)
  Clamping Voltage:
  - Voltage - Clamping (Max) @ Ipp
  Package Type:
  - Package / Case
  Temperature Range:
  - Operating Temperature
Connectors:
  Value:
  - Manufacturer Part Number
  Number of Contacts:
  - Number of Contacts
  - Number of Positions
  Number of Rows:
  Pitch:
  - Pitch
  Mounting Type: # (Surface Mount / Through-Hole / Mixed)
  - Mounting Type 
  Orientation: # (Vertical / Right-Angle)
  - Orientation
  Polarity: # (Plug / Receptacle)
  - Gender 
  Mating Height:
  Locking: # (Yes / No)
  - Locking Feature
  Shielding: # (Yes / No / Partial)
  - Shielding 
  Frequency:
  - Frequency - Max
  Interface Type:
  - Connector Type
  - Flat Flex Type
  Package Height:
  - Height Above Board
  Temperature Range:
  - Operating Temperature
Crystals and Oscillators:
  Value:
  - Frequency
  Rated Voltage:
  - Voltage - Supply
  Rated Current:
  - Current - Supply (Max)
  Frequency Stability:
  - Frequency Stability
  Frequency Tolerance:
  - Frequency Tolerance
  Load Capacitance:
  - Load Capacitance
  Temperature Range:
  - Operating Temperature
  Package Type:
  - Package / Case
  Package Size:
  - Size / Dimension
  Package Height:
  - Height - Seated (Max)
Diodes:
  Value:
  - Manufacturer Part Number
  Function Type:
  - Diode Type
  Forward Voltage:
  - Voltage - Forward (Vf) (Max) @ If
  - Voltage - Forward (Vf) (Typ)
  Rated Voltage:
  - Voltage - DC Reverse (Vr) (Max)
  - Voltage - Zener (Nom) (Vz)
  Rated Current:
  - Current - Average Rectified (Io)
  Rated Power:
  - Power - Max
  LED Color:
  - Color
  Temperature Range:
  - Operating Temperature
  - Operating Temperature - Junction
  Package Type:
  - Package / Case
Inductors:
  Value:
  - Inductance
  - Impedance @ Frequency
  Rated Current:
  - Current Rating (Max)
  - Current Rating (Amps)
  Saturation Current:
  - Current - Saturation
  ESR:
  - DC Resistance (DCR)
  - DC Resistance (DCR) (Max)
  Tolerance:
  - Tolerance
  Shielding:
  - Shielding
  Package Type:
  - Package / Case
  Package Size:
  - Size / Dimension
  Package Height:
  - Height - Seated (Max)
  Temperature Range:
  - Operating Temperature
Integrated Circuits:
  Value:
  - Manufacturer Part Number
  Number of Channels:
  - Channels per Circuit
  Frequency:
  - Clock Frequency
  - Speed
  - Data Rate
  - Frequency Range
  Rated Voltage:
  - Voltage - VCCA
  - Voltage - VCCB
  - Voltage - Supply
  - Voltage - Supply (Vcc/Vdd)
  - Voltage - Supply, Digital
  Function Type:
  - Translator Type
  - Technology
  - Core Processor
  - Type
  - Sensor Type
  Memory Size:
  - Program Memory Size
  - Memory Size
  Package Type:
  - Package / Case
  Temperature Range:
  - Operating Temperature
Mechanicals:
  Value:
  - Manufacturer Part Number
  Mounting Type:
  - Mounting Type 
  Rated Current:
  - Contact Rating @ Voltage
  Function Type:
  - Circuit
  Package Size:
  - Outline
  Temperature Range:
  - Operating Temperature
Power Management:
  Value:
  - Manufacturer Part Number
  Function Type:
  - Topology
  Min Input Voltage:
  - Voltage - Input (Min)
  Max Input Voltage:
  - Voltage - Input (Max)
  Output Type:
  - Output Type
  (Min) Output Voltage:
  - Voltage - Output (Min/Fixed)
  Max Output Voltage:
  - Voltage - Output (Max)
  Rated Current:
  - Current - Output
  Quiescent Current:
  - Current - Quiescent (Iq)
  Frequency:
  - Frequency - Switching
  Package Type:
  - Supplier Device Package
  Temperature Range:
  - Operating Temperature
Resistors:
  Value:
  - Resistance
  Rated Power:
  - Power (Watts)
  Tolerance:
  - Tolerance
  Package Type:
  - Supplier Device Package
  Temperature Range:
  - Operating Temperature
RF:
  Value:
  - Manufacturer Part Number
  Frequency:
  - Frequency Range
  Rated Voltage: null
  Function Type: null
  Package Type:
  - Package / Case
  Temperature Range:
  - Operating Temperature
Transistors:
  Value:
  - Manufacturer Part Number
  Function Type:
  - Transistor Type
  - FET Type
  Rated Current:
  - Current - Collector (Ic) (Max)
  - Current - Continuous Drain (Id) @ 25°C
  Rated Voltage:
  - Voltage - Collector Emitter Breakdown (Max)
  - Drain to Source Voltage (Vdss)
  Rated Power:
  - Power - Max
  - Power Dissipation (Max)
  Collector-Gate Voltage:
  - Vce Saturation (Max) @ Ib, Ic
  - Vgs(th) (Max) @ Id
  Maximum Gate Voltage:
  - Vgs (Max)
  RDS On Resistance:
  - Rds On (Max) @ Id, Vgs
  Package Type:
  - Supplier Device Package
  Temperature Range:
  - Operating Temperature
