name: Publish to PyPI

on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish_test:
    name: Build the package and publish to Test PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Wait for style check to succeed
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.ref }}
          check-name: "Style check"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.ref }}
          check-name: "Integration tests"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.6
        with:
          pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: "https://test.pypi.org/legacy/"
          ignore_dev_requirements: "yes"
