name: Style Checks

on:
  push:
    branches:
      - master
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - master

jobs:
  style:
    name: Style check
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -U flake8
      - name: PEP checks
        run: >
          flake8
          tasks.py
          kintree/kintree_gui.py
          run_tests.py
          kintree/setup_inventree.py
          kintree/common/
          kintree/config/
          kintree/database/
          kintree/kicad/__init__.py
          kintree/kicad/kicad_interface.py
          kintree/kicad/kicad_schlib.py
          kintree/kicad/schlib.py
          kintree/search/*.py
